{% set name = "gpkgstatus" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bc0c56a90b3fbfa2be5303665a862be707746702996e96f07746ab4dab506e35

build:
  entry_points:
    - gpkgstatus = gpkgstatus.entrypoint:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - requests ==2.28.2
    - termcolor ==2.2.0

test:
  imports:
    - gpkgstatus
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest -v tests
    - gpkgstatus -h

about:
  home: https://dkvc.github.io/gpkgstatus/
  summary: Get Current Package Status from Fedora Updates System
  description: |
    gpkgstatus is a command-line tool for checking the status of packages on bodhi.fedoraproject.org. 
    It allows you to search for a specific package and get information about its current status, including 
    the update ID, package name, and status.
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://dkvc.github.io/gpkgstatus/
  dev_url: https://github.com/dkvc/gpkgstatus/

extra:
  recipe-maintainers:
    - dkvc
